### ISSUE TITLE
Select Session not longer in Dashboard

### ISSUE THREAD

**Issue by antoinefalisse** [stanfordnmbl/opencap-viewer#149]
@AlbertoCasasOrtiz, I merged #147, but the `Select Session` button is still missing. I think it has to do with [this line](https://github.com/stanfordnmbl/opencap-viewer/blob/dev/src/components/pages/Dashboard.vue#L34) and the `session_owned`. The bug was probably incorporated as part of [this commit](https://github.com/stanfordnmbl/opencap-viewer/commit/afade401ce6009e2e89dd5a28060ec83c2fbc8b2). Any thoughts? Thanks.

Ps: the variable name suggests it is the case, but let's make sure users can only access their sessions.

**Comment by AlbertoCasasOrtiz** [comment]
Hi @antoinefalisse , I just tested this in the dev server and it is working for me. I tried with a session I own while logged in and `Select Session` is showing, then I tried without login in and it is not showing. This is the expected behaviour. If you try with other people's session, it should not show either.

**Comment by antoinefalisse** [comment]
Hi @AlbertoCasasOrtiz, when I log in as admin then I see it.

![image](https://github.com/stanfordnmbl/opencap-viewer/assets/19328993/7e09eac1-3831-42e4-b43b-5cdfc923954b)

but when I log in under my account, then I **do not** see it:

![image](https://github.com/stanfordnmbl/opencap-viewer/assets/19328993/57f98587-e6c2-4213-81ec-310b5b7ae1ae)

Let's follow up on slack to figure out what is best.
