### ISSUE TITLE
Ensure people are following license

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-viewer#245]
We need to directly ask people what they are using opencap for. Let's create a one-time pop up that asks them to select from the following options, and saves to a field in `user` called `institutional_use`

OpenCap is free for academic research and educational use (link Terms). Please identify how you use / intend to use OpenCap:

- Patient care
- Sports performance assessments
- Use in a company
- Research at an academic institution
- Teaching at an academic institution
- Other non-commercial activity

If any of the first 3, then the window says: 'This use is not a permitted use of OpenCap, please contact Model Health (admin@modelhealth.io) to purchase a license.'

Do we let them through and send an email, or somehow lock accounts?

@antoinefalisse

**Comment by AlbertoCasasOrtiz** [comment]
Since there is an option for "Other non-commercial activity", I would add explicitly add an option for "commercial use" as well.

This remembers me of [the profiles](https://github.com/stanfordnmbl/opencap-viewer/issues/7) issue for some reason.

Maybe we could implement profiles and ask people there (and at register time) what are they using opencap for. For people who already have an account, and has not answer the question, I would add a pop-up and redirect them there.

Regarding blocking accounts, I would show something like: "This use is not a permitted use of OpenCap, please contact Model Health ([admin@modelhealth.io](mailto:admin@modelhealth.io)) to purchase a license, or use OpenCap under the conditions of the academic license", and I would block until either they claim they will use opencap for things permitted by the academic license, or they purchase the commercial license.

We could even add an "upgrade for commercial use" button or something in that case, that opens a form asking for a commercial license and making it easier.

**Comment by antoinefalisse** [comment]
@suhlrich and @AlbertoCasasOrtiz summarizing here:

When users log in, we check if we have an entry into `institutional_use` in `user`.

- If not, there is pop up that asks them to select an option:
    -  OpenCap is free for academic research and educational use (link [Terms](https://www.opencap.ai/terms-conditions)). Please identify how you use / intend to use OpenCap:
        - Patient care
        - Sports performance assessments
        - Use in a company
        - Research at an academic institution
        - Teaching at an academic institution
        - Other non-commercial activity
    - If they select any of the first three options, the window says: 'This use is not a permitted use of OpenCap, please contact Model Health ([info@modelhealth.io](mailto:info@modelhealth.io)) to purchase a license.'
    - If they select any of the last three options, the user accesses the first screen
    - In both cases, the selected option is saved into `institutional_use` in `user`
- If yes
    - If the entry is one of the first three options above, a pop up window says: "Your previously indicated that you intended to use OpenCap for an application not permitted by the OpenCap license. Has you intended use changed? OpenCap is free for academic research and educational use (link [Terms](https://www.opencap.ai/terms-conditions)). Please identify how you use / intend to use OpenCap:
        - Patient care
        - Sports performance assessments
        - Use in a company
        - Research at an academic institution
        - Teaching at an academic institution
        - Other non-commercial activity" 
         - If they select any of the first three options, the window says: 'This use is not a permitted use of OpenCap, please contact Model Health ([info@modelhealth.io](mailto:info@modelhealth.io)) to purchase a license.'
     - If the entry is NOT one of the first options above, nothing happens and the user accesses the first screen. 

Let's not add an "upgrade for commercial use" button, this would be a COI.

I think we can adjust wording later, let's first agree on the logic.

**Comment by olehkorkh-planeks** [comment]
@antoinefalisse 
I prepared two PRs:

- Backend - https://github.com/stanfordnmbl/opencap-api/pull/148
- Frontend - https://github.com/stanfordnmbl/opencap-viewer/pull/265

I implemented the form as a separate page instead of a popup. I think it is logical.

https://share.cleanshot.com/L39NFc8c9BbrS8Hc3vTx
https://share.cleanshot.com/D81PLHwqrl2HF9hqLVLn
https://share.cleanshot.com/CZ6P3KPN0zFRstZ5Mlc1
https://share.cleanshot.com/F8jPwdFCbRMSZGtxNZWB

The "Submit" button is enabled only for the last three options. But, every time the user selects the option, the choice is saved on the backend. So, if he selects any of first three options and close the tab, next time he'll see a fixed message:

https://share.cleanshot.com/HmgltdjrVgnfxQwryRJW

**Comment by olehkorkh-planeks** [comment]
@antoinefalisse Fix - https://github.com/stanfordnmbl/opencap-viewer/pull/285
