### ISSUE TITLE
step2 n_devices connected error too fast

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-viewer#275]
If you have 0 phones connected, you get this error very briefly: 
![image](https://github.com/stanfordnmbl/opencap-viewer/assets/43877159/f2aab797-4d19-4fc3-98c8-9d4a2c258fe8)
followed by this error
![image](https://github.com/stanfordnmbl/opencap-viewer/assets/43877159/46ec614a-0b65-4990-81e3-b5babb3dbf57).

It would be nice if the first error did not disappear so quickly, but they both appeared for 10s each.

**Comment by AlbertoCasasOrtiz** [comment]
Hi @suhlrich, I tried to reproduce this error with no success. I created a new session, and I clicked next without connecting any device. Then, I clicked "Calibrate", but only the first error appears to me.

Did you connect a device, and then disconnected it? Maybe the reason I am not getting the second error is that it is not expecting any device to upload videos since I didn't connect one.
