### ISSUE TITLE
Notify if a phone is frozen

### ISSUE THREAD

**Issue by suhlrich** [stanfordnmbl/opencap-viewer#78]
Currently, a phone may freeze, and the user would proceed through collection without getting errors that one phone isn't uploading videos until they have been pushed thru the back end. We are trying to fix on phone side, but let's also throw an informative error. A video instance is not created in the database for the phone if it is frozen, so we can compare video instances from each trial to the calibration.

1) On the API, when the `...sessions/<session_id>/stop` is called, if it is not a calibration trial, let's check to see if the number of video instances (regardless of if the video is uploaded or not) for that trial is the same as the number in the most recent calibration trial (make sure to sort these by date and pick the newest one). If nVideos(thisTrial) != nVideos(calibration), throw an error with those actual numbers. Put the error text in trial['meta']['error_msg'].
2) Front end, if we get an error back from the `/stop/` endpoint, display it for both Step 4 and Step 5. Switching to `apiErrorRes()` would work.

**Comment by AlbertoCasasOrtiz** [comment]
This PR should fix this issue:
https://github.com/stanfordnmbl/opencap-api/pull/41

**Comment by AlbertoCasasOrtiz** [comment]
Hi! I am working on that issue, and there are two cases:

1. The session has a calibration trial.
1. The session was created from another session (that either has a calibration trial, or was created from another session that has a calibration trial...)

No major problems here, since it is a simple recursive problem, but, what should I do in the case that the original session, having the calibration trial, was removed? This is what is happening for my testing session:
`90e869e9-34d8-4235-b989-aec3df23e764`

**Comment by antoinefalisse** [comment]
@AlbertoCasasOrtiz I reverted the PR to clean-up the dev api: https://github.com/stanfordnmbl/opencap-api/pull/53
Let's have 2FA finished and fixed, then we can merge that PR, test, and close the issue.
Thanks.
